server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        set $catalog_backend http://backend:8000;
        proxy_pass $catalog_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /posters/ {
        set $catalog_minio http://minio:9000;
        proxy_pass $catalog_minio;
        proxy_set_header Host $proxy_host;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
